name: Publish compress-nodejs example to release
on:
  push:
    branches: [ master, main ]
  release:
    types: [published]
jobs:
  build:
    permissions:
      contents: write
      packages: write
      repository-projects: write
      actions: write
      deployments: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      #
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      #
      - run: cd example && npm i
      - run: cd example && npm run prepare
      - run: cd example && npm run build
      #
      - name: Zip files for release
        run: zip -r compress-nodejs-example-${{ steps.vars.outputs.tag }}.zip example/dist/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./compress-nodejs-example-${{ steps.vars.outputs.tag }}.zip  # Adjust according to your build output directory
          asset_name: compress-nodejs-example-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #