name: Publish Package to npmjs
on:
  #push:
  #  branches: [ master, main ]
  release:
    types: [published]
jobs:
  build:
    permissions:
      contents: read
      packages: write
      repository-projects: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run prepare
      - run: npm run build
      #
      - name: Zip files for release
        run: zip -r build.zip dist/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build.zip  # Adjust according to your build output directory
          asset_name: build.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}